### ISSUE TITLE
colName when have agg func

### ISSUE THREAD

**Issue by iwanttobepowerful** [skyzh/bustub-web-shell#1]
```
D select max(a), min(a) from t1;
┌────────┬────────┐
│ max(a) │ min(a) │
├────────┼────────┤
│ 3      │ 1      │
└────────┴────────┘
```
![image](https://user-images.githubusercontent.com/30350667/194734415-880b3fe5-bdb4-4ff3-9ada-6eedb11b6f2d.png)

**Comment by skyzh** [comment]
We don't ensure 100% compatibility with other systems. Also for bug reports go to https://github.com/cmu-db/bustub/issues.
